sudo: required
services:
  - docker

before_install:
  - docker build -t yeshwant124/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yeshwant124/docker-react npm run test -- --coverage