sudo: required
services:
  - docker

before_install:
  - docker build -t yeshwant/docker-react-1 -f Dockerfile.dev .

script:
  - docker run -e CI=true yeshwant/docker-react-1 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306785467"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"